//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoHyperstar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost;DataBase=postgis2;Port=5432;Userid=postgres;password=wangyiqi")]
        public string Mesh533935 {
            get {
                return ((string)(this["Mesh533935"]));
            }
            set {
                this["Mesh533935"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost;DataBase=postgis3;Port=5432;Userid=postgres;password=wangyiqi")]
        public string USNetwork {
            get {
                return ((string)(this["USNetwork"]));
            }
            set {
                this["USNetwork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost;DataBase=postgis1;Port=5432;Userid=postgres;password=wangyiqi")]
        public string TestNetwork {
            get {
                return ((string)(this["TestNetwork"]));
            }
            set {
                this["TestNetwork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost;DataBase=postgis1;Port=5432;Userid=postgres;password=wangyiqi")]
        public string DefaultCon {
            get {
                return ((string)(this["DefaultCon"]));
            }
            set {
                this["DefaultCon"] = value;
            }
        }
    }
}
